#!/bin/sh

# Simple install script for vcc
# Author: Michael Tobin
# Last updated: 15 August 2003

echo  "Have you modified src/config.h? (yes/no) "
read config

if [ "$config" != "yes" -a "$config" != "y" ]
then
	${EDITOR:-vim} src/config.h
fi

cd src
make
make install


