/*
 *	count.c
 *
 *	For those interested in comparing hand written assembly code
 *	to code generated by the compiler, this program is meant to mimic
 *	the behavior of the count.asm program included with the vasm
 *	distribution.
 *
 *	If you compile this program with the -a option and compare the output
 *	to count.asm, you'll notice this is about 5 or 6 times longer.
 *	So writing assembly code by hand IS more efficient.  But now, look
 *	at the output from qsort.c, and think about writing a quick sort
 *	routine in assembly code by hand...the compiler's good for something.
 */

int main()
{
	int a, b;
	
	a = 10;
	b = 0;
	
	while (a > 0)
	{
		++b;
		--a;
	}
	return 0;
}
