/*
 *	config.h
 *
 *	While many times this file would be generated by a configure
 *	script, I don't want to deal with those.  So you need to manually
 *	edit this file so the macros point to the proper binary files.
 *
 *	If you are unsure where the cpp binary is, simply run the command
 *		
 *		% which cpp
 *
 *	From the shell and copy the output to the CPP macro.
 *
 *	VASM should be located in a directory close by.  For the fewest
 *	problems, use the complete path to the assembler
 *	i.e., /home/ugrads/tobin/vespa/vasm/vasm and not ../vasm/vasm
 *
 *	Author: Michael Tobin
 *	Last updated: 13 August 2003
 */
 
#ifndef	__CONFIG_INCLUDED__
#define __CONFIG_INCLUDED__

#define	CPP	"/usr/local/bin/cpp"
#define VASM	"../../compiler/vasm/vasm"

#endif
 
